### POST - Create a new log
POST http://localhost:4000/logs
Content-Type: application/json

{
  "clientId": 1,
  "osId": 1,
  "deviceId": 1,
  "params": "{}",
  "method": "GET",
  "message": "Not Modified",
  "router": "/users",
  "ip": "::1",
}

### GET - Get all logs in database
GET http://localhost:4000/logs